# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: af928720f4dc0b0a2b69f1a8d78a231c4afec439bdc4927550dd52f1910a94287d2fc454f2e73cca686da9eb54426e18aa0051e2edbc0146798a8b648397c964

test:
  secret_key_base: 9ad253ab7e923f11dec322df69f25f04e84ec8c1b7cd14fcc82e5cdc156f4023fa7180436ecb230749b103d57503f05e568991a91502269af4cbcc012cff3a0f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
